{% set name = "fbdfile" %}
{% set version = "2025.9.17" %}
{% set sha256 = "7e3748f036706c116d91b909ab3bf38839984487c9bce714df00e315f71ffac8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [py<311]
  entry_points:
    - fbdfile = fbdfile.fbdfile:main
    - fbd2b64 = fbdfile.fbd2b64:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.1.3                         # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
  host:
    - python
    - setuptools >=68
    - numpy
    - cython >=3.1.3
    - pip
  run:
    - python
    - numpy
    - click
    - matplotlib-base
    - tifffile >=2024.8.30

test:
  imports:
    - fbdfile
  commands:
    - pip list
    - pip check
    - fbdfile --help
    - fbd2b64 --help
  requires:
    - pip

about:
  home: https://www.cgohlke.com
  summary: Read FLIMbox data and related files (FBD, FBF, FBS.XML)
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    Fbdfile is a Python library to read FLIMbox data (FBD), firmware (FBF), and setting (FBS.XML) files.
  dev_url: https://github.com/cgohlke/fbdfile

extra:
  recipe-maintainers:
    - cgohlke
